# Generated by Django 4.0.5 on 2023-08-05 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_uploadvideo_video_file_uploadvideo_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('suggestion', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='about_us',
            options={'verbose_name_plural': 'about_us'},
        ),
        migrations.AlterModelOptions(
            name='customer_reviews',
            options={'verbose_name_plural': 'customer_reviews'},
        ),
        migrations.AlterModelOptions(
            name='uploadgallery',
            options={'verbose_name_plural': 'uploadGallery'},
        ),
    ]
